# Generated by Django 3.2.12 on 2022-04-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproject',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
