# Generated by Django 3.2.12 on 2022-04-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uploadproject_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadproject',
        ),
    ]
