# Generated by Django 3.2.12 on 2022-04-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
