# Generated by Django 3.2.12 on 2022-04-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadproject',
        ),
    ]
