# Generated by Django 3.2.12 on 2022-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_uploadproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to='')),
                ('img2', models.ImageField(upload_to='')),
                ('img3', models.ImageField(upload_to='')),
                ('img4', models.ImageField(upload_to='')),
                ('img5', models.ImageField(upload_to='')),
                ('img6', models.ImageField(upload_to='')),
                ('img7', models.ImageField(upload_to='')),
                ('img8', models.ImageField(upload_to='')),
                ('img9', models.ImageField(upload_to='')),
                ('img10', models.ImageField(upload_to='')),
                ('img11', models.ImageField(upload_to='')),
                ('img12', models.ImageField(upload_to='')),
                ('img13', models.ImageField(upload_to='')),
                ('img14', models.ImageField(upload_to='')),
                ('img15', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=1000)),
                ('discription', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Uploadproject',
            },
        ),
    ]
