# Generated by Django 3.2.12 on 2022-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_uploadproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfoliopage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Portfoliopage',
            },
        ),
    ]
