# Generated by Django 3.2.12 on 2022-04-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_portfoliopage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfoliopage',
            table=None,
        ),
    ]
