# Generated by Django 3.2.12 on 2022-04-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_portfoliopage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='portfoliopage',
            table='Portfoliopage',
        ),
    ]
