# Generated by Django 3.2.12 on 2022-04-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_portfoliopage_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfoliopage',
        ),
        migrations.DeleteModel(
            name='Uploadproject',
        ),
    ]
