# Generated by Django 3.2.12 on 2022-04-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_portfoliopage_uploadproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='msg',
            new_name='phone',
        ),
    ]
