# Generated by Django 3.2.12 on 2022-04-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_msg_contacts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
