# Generated by Django 3.2.12 on 2022-05-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_sitedata_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='note',
            new_name='date',
        ),
    ]
