# Generated by Django 3.2.12 on 2022-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_note_sitedata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitedata',
        ),
    ]
