# Generated by Django 3.2.12 on 2022-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_sitedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citename', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Sitedata',
            },
        ),
    ]
