# Generated by Django 3.2.12 on 2022-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sitedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitedata',
        ),
    ]
