# Generated by Django 3.2.12 on 2022-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_sitedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadproject',
            name='img10',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img11',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img12',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img13',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img14',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img15',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img7',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img8',
        ),
        migrations.RemoveField(
            model_name='uploadproject',
            name='img9',
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img1',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
