# Generated by Django 3.2.12 on 2022-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220523_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproject',
            name='img1',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
