# Generated by Django 3.2.12 on 2022-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_uploadproject_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproject',
            name='img1',
            field=models.FileField(upload_to='images/'),
        ),
    ]
