# Generated by Django 3.2.12 on 2022-05-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220523_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
