# Generated by Django 3.2.12 on 2022-05-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_multipleimage_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
