# Generated by Django 3.2.12 on 2022-05-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20220524_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
