# Generated by Django 3.2.12 on 2022-05-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_multipleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Personaldetail',
        ),
        migrations.DeleteModel(
            name='Portfoliopage',
        ),
        migrations.DeleteModel(
            name='Uploadproject',
        ),
    ]
