# Generated by Django 3.2.12 on 2022-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0041_auto_20220524_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Personaldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Personaldetail',
            },
        ),
        migrations.CreateModel(
            name='Portfoliopage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Portfoliopage',
            },
        ),
        migrations.CreateModel(
            name='Uploadproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img1', models.FileField(blank=True, upload_to='')),
                ('img2', models.ImageField(blank=True, upload_to='')),
                ('img3', models.ImageField(blank=True, upload_to='')),
                ('img4', models.ImageField(blank=True, upload_to='')),
                ('img5', models.ImageField(blank=True, upload_to='')),
                ('img6', models.ImageField(blank=True, upload_to='')),
                ('img7', models.ImageField(blank=True, upload_to='')),
                ('img8', models.ImageField(blank=True, upload_to='')),
                ('img9', models.ImageField(blank=True, upload_to='')),
                ('img10', models.ImageField(blank=True, upload_to='')),
                ('img11', models.ImageField(blank=True, upload_to='')),
                ('img12', models.ImageField(blank=True, upload_to='')),
                ('img13', models.ImageField(blank=True, upload_to='')),
                ('img14', models.ImageField(blank=True, upload_to='')),
                ('img15', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=1000)),
                ('discription', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Uploadproject',
            },
        ),
    ]
