# Generated by Django 3.2.12 on 2022-05-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_multipleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
