# Generated by Django 3.2.12 on 2022-05-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_delete_multipleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfoliopage',
        ),
        migrations.DeleteModel(
            name='Uploadproject',
        ),
    ]
