# Generated by Django 3.2.12 on 2022-05-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_rename_location_photo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
