# Generated by Django 3.2.12 on 2022-05-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20220526_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfoliopage',
        ),
        migrations.DeleteModel(
            name='Uploadproject',
        ),
    ]
