# Generated by Django 3.2.12 on 2022-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_portfoliopage_uploadproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproject',
            name='img1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img10',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img11',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img12',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img13',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img14',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img15',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img6',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img7',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img8',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadproject',
            name='img9',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
