# Generated by Django 3.2.12 on 2022-05-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_portfoliopage_uploadproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Personaldetail',
        ),
        migrations.DeleteModel(
            name='Portfoliopage',
        ),
        migrations.DeleteModel(
            name='Uploadproject',
        ),
    ]
